// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zritiseifgxtjrocgyfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyaXRpc2VpZmd4dGpyb2NneWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTY0MTAsImV4cCI6MjA2MjY5MjQxMH0.O4PhZ4EIihrdV7uDfNZdMPsL7a83m982YD8HIuxUWHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);